# Generated by Django 5.1.5 on 2025-02-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_transferhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferhistory',
            name='t_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='from_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='t_product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='to_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
