# Generated by Django 5.1.5 on 2025-02-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_transferhistory_t_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferhistory',
            name='t_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
