# Generated by Django 5.1.5 on 2025-02-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_order_order_total_orderdetails_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_shipping',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='od_prodname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
