# Generated by Django 5.1.5 on 2025-02-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_order_order_shipping_orderdetails_od_prodname'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='od_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('TO PAY', 'TO PAY'), ('TO SHIP', 'TO SHIP'), ('TO RECEIVE', 'TO RECEIVE'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=50),
        ),
    ]
