# Generated by Django 5.1.5 on 2025-02-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0010_order_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_status',
            field=models.CharField(choices=[('ORDERED', 'ORDERED'), ('PENDING', 'PENDING'), ('DONE', 'DONE')], default='PENDING', max_length=50),
        ),
    ]
