# Generated by Django 5.1.5 on 2025-02-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0011_cart_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='contact_no',
            field=models.CharField(default='+63000000000', max_length=12),
        ),
    ]
